# Generated by Django 6.0.2 on 2026-02-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_author_id_alter_book_id_alter_publishing_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors',
            new_name='author',
        ),
    ]
