# Generated by Django 6.0.2 on 2026-02-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_authors_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='registered_at',
        ),
    ]
