# Generated by Django 6.0.2 on 2026-02-10 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reader_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='registered_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
