# Generated by Django 6.0.2 on 2026-02-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reader_registered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Not specified'), (1, 'Male'), (2, 'Female'), (3, 'Other')], default=0),
        ),
        migrations.AddField(
            model_name='reader',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publishing',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
